name: Playstore internal test deployment
on:
  workflow_dispatch:
    inputs:
      branch:
        description: "Branch a ejecutar"
        required: true
        default: "develop"

jobs:
  deploy_android_internal_test:
    name: Deploying to playstore Internal testing
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./android

    steps:
      - name: Checkout branch
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.0
          bundler-cache: true

      - name: Cache Ruby - Bundler
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Setup Java
        uses: actions/setup-java@v5
        with:
          java-version: 17.x
          distribution: "zulu"

      - name: Cache Gradle
        uses: actions/cache@v4
        with:
          path: ~/.gradle/caches/
          key: cache-clean-gradle-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Cache Gradle Wrapper
        uses: actions/cache@v4
        with:
          path: ~/.gradle/wrapper/
          key: cache-clean-wrapper-${{ matrix.os }}-${{ matrix.jdk }}

      - name: Configure Keystore and key properties
        env:
          ANDROID_UPLOAD_SIGNATURE: ${{ secrets.ANDROID_UPLOAD_SIGNATURE }}
          KEYSTORE_KEY_ALIAS: ${{ secrets.KEYSTORE_KEY_ALIAS }}
          KEYSTORE_KEY_PASSWORD: ${{ secrets.KEYSTORE_KEY_PASSWORD }}
          KEYSTORE_STORE_PASSWORD: ${{ secrets.KEYSTORE_STORE_PASSWORD }}
        run: |
          echo "$ANDROID_UPLOAD_SIGNATURE" > keystore.jks.b64
          base64 -d -i keystore.jks.b64 > app/keystore.jks
          echo "storeFile=keystore.jks" >> key.properties
          echo "keyAlias=$KEYSTORE_KEY_ALIAS" >> key.properties
          echo "storePassword=$KEYSTORE_STORE_PASSWORD" >> key.properties
          echo "keyPassword=$KEYSTORE_KEY_PASSWORD" >> key.properties

      - name: Configure json file
        env:
          PLAY_CONFIG_JSON: ${{ secrets.PLAY_CONFIG_JSON }}
        run: |
          echo "$PLAY_CONFIG_JSON" > service_account_key.json.b64
          base64 -d -i service_account_key.json.b64 > service_account_key.json

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter --version

      - name: Clean Flutter project
        run: flutter clean

      - name: Install Flutter dependencies
        run: flutter pub get

      - name: Build the appbundle
        run: flutter build appbundle --no-tree-shake-icons --release --build-number 1${GITHUB_RUN_NUMBER}

      - name: Install bundle
        run: |
          gem install bundler
          bundle update
          bundle install

      - name: Init supply
        run: bundle exec fastlane supply init --verbose

      - name: Distribute app to internal track ðŸš€
        env:
          ANDROID_UPLOAD_SIGNATURE: ${{ secrets.PLAY_CONFIG_JSON }}
        run: bundle exec fastlane deployInternalToPlaystore
